apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: weichengjian
  name: automatic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weichengjian
  template:
    metadata:
      labels:
        app: automatic
    spec:
      imagePullSecrets:
        - name: weichengjian-secret
      containers:
        - name: automatic
          env:
            - name: ENV
              value: prod
          image: weichengjian/imagename
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9000
