apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: weichengjian
  name: automatic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: automatic
  template:
    metadata:
      labels:
        app: automatic
    spec:
      imagePullSecrets:
        - name: weichengjian-secret
      containers:
        - name: automatic
          env:
            - name: ENV
              value: prod
          image: weichengjian/imagename
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9000
     containers:
    -mountPath: /etc/localtime
      name: vol-localtime
      readOnly: true
    volumes:
        -name: vol-localtime
        hostpath:
            path: /etc/localtime
       spec:
        hostAliases:
           - ip: "xx.xxx.xx.xxx"
        hostnames:
         - "mysql-master"
         - "proxysql-server"
         - "redis-server"
        strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 25%
       maxSurge: 25%
revisionHistoryLimit: 10
progressDeadlineSeconds: 600
       env:
    -name: JAVA_OPTS
    value: >-
       -Duser.timezone=Asia/Shanghai
