apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: weichengjian
  name: automatic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: automatic
  template:
    metadata:
      labels:
        app: automatic
    spec:
      #imagePullSecrets:
        #- name: wcj-secret
      containers:
        - name: automatic
          #env:
            #- name: ENV
             # value: prod
          image: 192.168.10.10:10001/automatic/golang
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9000
