apiVersion: v1
kind: Service
metadata:
  name: automatic
  namespace: weichengjian
spec:
  type: NodePort
  selector:
    app: automatic
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30001
